/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_navitek_jni_RoiNoduleDetection */

#ifndef _Included_RoiNoduleDetectionJNI
#define _Included_RoiNoduleDetectionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_navitek_jni_RoiNoduleDetection
* Method:    SemiAutoLungNodulesDetection
* Signature: (Ljava/lang/String;Lcom/navitek/jni/RegionInfo;[S[S)Lcom/navitek/jni/RoiNoduleInfoList;
*/
JNIEXPORT jobject JNICALL Java_com_navitek_jni_RoiNoduleDetection_SemiAutoLungNodulesDetection
(JNIEnv *, jobject, jstring, jobject, jbooleanArray, jintArray);


#ifdef __cplusplus
}
#endif
#endif
